### ISSUE TITLE
IMixedRealityPointer errors on import of SDK 0.1.13

### ISSUE THREAD

**Issue by milos12345** [XRTK/XRTK-Core#349] opened 2019-09-20 01:37 UTC
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

On import of SDK 0.1.13 there is a bunch of errors preventing play

```
Library\PackageCache\com.xrtk.sdk@0.1.13\Features\UX\Scripts\Pointers\MousePointer.cs(18,56): error CS0535: 'MousePointer' does not implement interface member 'IMixedRealityPointer.SyncedTarget'

Library\PackageCache\com.xrtk.sdk@0.1.13\Features\UX\Scripts\Pointers\MousePointer.cs(18,56): error CS0535: 'MousePointer' does not implement interface member 'IMixedRealityPointer.OverrideGrabPoint'

Library\PackageCache\com.xrtk.sdk@0.1.13\Features\UX\Scripts\Pointers\TouchPointer.cs(15,56): error CS0535: 'TouchPointer' does not implement interface member 'IMixedRealityPointer.SyncedTarget'

Library\PackageCache\com.xrtk.sdk@0.1.13\Features\UX\Scripts\Pointers\TouchPointer.cs(15,56): error CS0535: 'TouchPointer' does not implement interface member 'IMixedRealityPointer.OverrideGrabPoint'

Library\PackageCache\com.xrtk.sdk@0.1.13\Features\UX\Scripts\Pointers\BaseControllerPointer.cs(29,9): error CS0535: 'BaseControllerPointer' does not implement interface member 'IMixedRealityPointer.SyncedTarget'

Library\PackageCache\com.xrtk.sdk@0.1.13\Features\UX\Scripts\Pointers\BaseControllerPointer.cs(29,9): error CS0535: 'BaseControllerPointer' does not implement interface member 'IMixedRealityPointer.OverrideGrabPoint'
```

## To Reproduce

Start Hub
New Project with 2019.1.14f1; 3D
Modify manifest to include 0.1.20
In Package Manager add  XRTK.WindowsMixedReality 0.1.6
Add XRTK.SDK 0.1.13
Errors show up

## Your Setup (please complete the following information)

- Unity Version 2019.1.14f1
- XRTK Version 0.1.8

## Target Platform (please complete the following information)

- OpenVR

## Additional context

HP WMR

**Comment by StephenHodgson** [comment] 2019-09-20 13:29
The SDK release for `com.xrtk.core` has not been release yet

**Comment by StephenHodgson** [comment] 2019-09-20 13:36
Duplicate of https://github.com/XRTK/SDK/issues/90

**Closed** 2019-09-22 23:36 UTC
Labels: Bug, Duplicate
