### ISSUE TITLE
Unity crashes on a new project with first time XRTK import

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#174] opened 2019-05-09 19:29 UTC
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug
Unity crashwhollops (technical term) on a brand new project and we setup XRTK.

## To Reproduce
1. Create new project
2. Import XRTK
3. Click Mixed Reality Toolkit -> Configure
4. Boom

## Expected behavior
Unity should not crash (and we should have world peace while we are at it)

## Actual behavior
BadabingBadaboom.    Because... Unity

## Your Setup (please complete the following information)

- Unity Version 2019.1.1
- XRTK Version 0.1.10

## Target Platform (please complete the following information)

Any

**Comment by SimonDarksideJ** [comment] 2019-05-09 20:54
Submitted #175 to resolve the Unity issue.

**Comment by SimonDarksideJ** [comment] 2019-05-12 21:28
Need to retest once the latest version is up to ensure the bug is resolved.

**Comment by StephenHodgson** [comment] 2019-05-13 00:13
I had, but I'll let you close it once you've validated :)

**Comment by SimonDarksideJ** [comment] 2019-05-19 10:07
Still crashing in 1.11 :S

**Comment by StephenHodgson** [comment] 2019-05-19 14:59
I cannot reproduce this with your steps. Is there something else I'm missing?

**Comment by SimonDarksideJ** [comment] 2019-05-22 00:39
Appears to be a deep routed Unity bug, will have to provide documentation to workaround it for now.
#183

**Comment by StephenHodgson** [comment] 2019-05-23 23:23
@SimonDarksideJ do you have a case number for tracking purposes?

**Comment by SimonDarksideJ** [comment] 2019-05-23 23:43
Unity bug tracking ref:
https://fogbugz.unity3d.com/default.asp?1155807_rpps8djd63j0n3cs

**Comment by StephenHodgson** [comment] 2019-09-16 16:14
Any update to this.

I know we've narrowed it down to the SDK package specifically using the default configuration profile.

**Comment by StephenHodgson** [comment] 2019-09-16 16:17
I saw you opened a new bug report on this: https://fogbugz.unity3d.com/default.asp?1184509_lkg3v0pa94vntobc

**Comment by SimonDarksideJ** [comment] 2019-09-16 22:10
Solved for GitHub based UPM implementation. But now that we have moved to a UPM server, it's back again....

**Comment by StephenHodgson** [comment] 2019-09-23 14:20
Hasn't seemed to be fixed yet. Let's try adding a delay call to the [`Selection.activeObject` on line 130](https://github.com/XRTK/XRTK-Core/pull/337/files#diff-47b2b78b056dfdf89a3953f9d75591efR130)

**Comment by SimonDarksideJ** [comment] 2019-09-24 19:48
Errors detected by Unity 2019.2 (although it doesn't crash, you have to reboot to make it work again :D )
```
An AssetDatabase Refresh is pending after a successful Package Manager request. You should not call AssetDatabase.Refresh at this time because it can lead to import-related errors.
UnityEditor.AssetDatabase:Refresh(ImportAssetOptions)
XRTK.Utilities.Editor.MixedRealityEditorSettings:CheckSettings() (at Library/PackageCache/com.xrtk.core@0.1.20/Utilities/Editor/MixedRealityEditorSettings.cs:178)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()

InvalidOperationException: Hierarchy change detected while computing layout, this is not supported.
UnityEngine.UIElements.UIRLayoutUpdater.OnVersionChanged (UnityEngine.UIElements.VisualElement ve, UnityEngine.UIElements.VersionChangeType versionChangeType) (at C:/buildslave/unity/build/Modules/UIElements/Renderer/UIRLayoutUpdater.cs:29)
UnityEngine.UIElements.VisualTreeUpdater.OnVersionChanged (UnityEngine.UIElements.VisualElement ve, UnityEngine.UIElements.VersionChangeType versionChangeType) (at C:/buildslave/unity/build/Modules/UIElements/VisualTreeUpdater.cs:101)
UnityEngine.UIElements.Panel.OnVersionChanged (UnityEngine.UIElements.VisualElement ve, UnityEngine.UIElements.VersionChangeType versionChangeType) (at C:/buildslave/unity/build/Modules/UIElements/Panel.cs:652)
UnityEngine.UIElements.VisualElement+Hierarchy.Clear () (at C:/buildslave/unity/build/Modules/UIElements/VisualElementHierarchy.cs:361)
UnityEngine.UIElements.VisualElement.Clear () (at C:/buildslave/unity/build/Modules/UIElements/VisualElementHierarchy.cs:133)
UnityEditor.InspectorWindow.RebuildContentsContainers () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:712)
UnityEditor.InspectorWindow.RedrawFromNative () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:324)
UnityEditor.AssetDatabase:SaveAssets()
XRTK.Extensions.LayerExtensions:SetupLayer(Int32, String) (at Library/PackageCache/com.xrtk.core@0.1.20/Extensions/LayerExtensions.cs:156)
XRTK.Services.MixedRealityToolkit:InitializeServiceLocator() (at Library/PackageCache/com.xrtk.core@0.1.20/Services/MixedRealityToolkit.cs:425)
XRTK.Services.MixedRealityToolkit:ResetConfiguration(MixedRealityToolkitConfigurationProfile) (at Library/PackageCache/com.xrtk.core@0.1.20/Services/MixedRealityToolkit.cs:117)
XRTK.Inspectors.MixedRealityToolkitInspector:OnInspectorGUI() (at Library/PackageCache/com.xrtk.core@0.1.20/Inspectors/MixedRealityToolkitInspector.cs:99)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Assertion failed
UnityEditor.RetainedMode:UpdateSchedulers()

Assertion failed
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by StephenHodgson** [comment] 2019-10-01 16:30
@SimonDarksideJ you confirmed this is fixed?

**Comment by SimonDarksideJ** [comment] 2019-10-01 16:47
Confirmed, the crash fix does appear resolved.  However, we are no longer receiving the prompt to configure the platform. (XR settings and IL2CPP)

**Comment by StephenHodgson** [comment] 2019-10-01 16:48
Sounds like a new bug report to me.

**Comment by SimonDarksideJ** [comment] 2019-10-01 16:52
I think I'm fine with that

**Comment by StephenHodgson** [comment] 2019-10-01 17:34
This still happened for me with 2019.1.14 and xrtk core 0.1.21

**Closed** 2019-12-16 18:43 UTC
Labels: Bug, Unity Bug
