### ISSUE TITLE
Add a "Clone" button to the actual profile window and not just the parent screen

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#435] opened 2020-01-07 13:57 UTC
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Currently, when wanting to clone and create your own configuration for a service/feature, you have to navigate back to the Parent profile in order to clone it

## How would you classify your suggestion

- Usability / Configuration

## Describe the solution you'd like

There should be a button in each profile (called "Clone") that will clone the current profile and create a new one in exactly the same way as it does in the parent profile.

This will avoid users having to painfully navigate at times to find the profile they want to clone.

Additionally, it would be nice if this was also recursive, so once you are on a profile you want to clone, it will also clone any parent "default" profiles, saving many clicks.
## Describe alternatives you've considered

An alternative would be to clone the entire default configuration to a users project, thus avoiding having to clone at all.  Providing there was an option to "reset to default" and copy the defaults back again.

**Comment by StephenHodgson** [comment] 2020-01-07 14:05
There's already a way to clone profiles

**Comment by StephenHodgson** [comment] 2020-01-07 14:14
Check out the context menu on any profile.

Adding this would duplicate an existing ux control pixels away from the purposefully designed control to match the editor patterns and ux design.

**Comment by SimonDarksideJ** [comment] 2020-01-07 14:51
This is about cloning the profile you are actually looking at, instead of forcing the user to navigate away to find it and clone again. It's a UX issue

**Comment by StephenHodgson** [comment] 2020-01-07 14:58
Okay then it's a duplicate of #35

**Closed by StephenHodgson** 2020-01-07 14:58 UTC
Labels: Feature Request
