### ISSUE TITLE
Configuration should verify there are no broken links in profile configuration that prevent a package running

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#707] opened 2020-11-29 17:55 UTC
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

During the course of testing #706, invalid / broken reference links in profile configuration (specifically pointers in this case) caused a project to fail only at runtime, there was no indication in the editor that there was an issue.

The errors reported were spurious and not easy to diagnose what was in effect, a simple configuration issue.

## To Reproduce

Run steps identified in #706 and run the project with controllers attached

## Expected behavior

Configuration errors or bad references should be identified IN the editor, before running the project

## Actual behavior

Bad things happen

## Your Setup

- Operation system ALL
- Unity Version 2019.4
- XRTK Version 0.2-preview

**Comment by StephenHodgson** [comment] 2020-12-13 02:10
Wouldn't say this is a bug so much as a safety check/enhancement, no?

**Comment by StephenHodgson** [comment] 2020-12-13 03:56
> Run steps identified in #706 and run the project with controllers attached

Duplicate of #706

**Closed by StephenHodgson** 2020-12-13 03:56 UTC
Labels: Bug
