### ISSUE TITLE
XRTK - First time install

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#173] opened 2019-05-09 10:54 UTC
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug
When first installing the XRTK via the UPM package manager, everything is installed by default.  This creates a bit of a jarring experience with multiple installs running over and over.

## To Reproduce
Steps to reproduce the behaviour:
1. Add XRTK to the manifest.json
2. Return to Unity

## Expected behaviour
XRTK should be installed and it should then be possible to add more platforms as desired.

## Actual behaviour
Everything is on, cannot easily through the Confg profile remove platforms and forced to use the UPM manager to remove afterwards.
Unity project is unusable for a few minutes while the packages are imported.

## Your Setup (please complete the following information)

- Unity Version 2019.1.0f2
- XRTK Version 0.1.10

## Target Platform (please complete the following information)

New project, user might not be sure which to start with.

**Comment by StephenHodgson** [comment] 2019-05-09 17:29
Not sure this is a bug as it's the intended behavior to install the default packages.

Could it be faster? Yes. I wonder if moving to npm will make that faster.

**Comment by SimonDarksideJ** [comment] 2019-05-09 21:10
My view after playing with it some more with my "New user" hat on (and judging from the feedback I've heard from MR dev days).
People want to start small and then add more platforms on.  So having just the Core, maybe the SDK as on by default is enough.  Then users can add WMR / Lumin / etc later once they are ready (or are targetting those platforms)

ALL ON by default just slows down the new project experience.

**Comment by StephenHodgson** [comment] 2019-05-10 01:20
I understand, but maybe we can do like Unity and pull in the package specifically for that build target?

**Comment by SimonDarksideJ** [comment] 2019-05-10 12:11
Possibly, however only UWP is separate atm.
Maybe put it to a poll on the XRTK Public chat?

**Comment by SimonDarksideJ** [comment] 2019-05-23 11:48
Survey seemed to indicate developers would like an Opt-In model.  Thoughts @StephenHodgson on how to achieve this?
Would only affect UPM setup, not Clone / Submodules

**Comment by StephenHodgson** [comment] 2019-05-23 23:23
Should be easy enough to do by updating the default package profile

**Comment by SimonDarksideJ** [comment] 2019-05-24 11:38
An ancillary bug to look at in relation to packages @StephenHodgson , seems you can't uninstall the packages and have them stay uninstalled :S
SO when you remove the package using the "Mixed Reality -> Packages" screen, they are re-installed when you open Unity again :D

**Comment by StephenHodgson** [comment] 2019-05-25 22:06
That was part of the serialization bug with the package profile I mentioned earlier. I should probably log that bug.

**Comment by SimonDarksideJ** [comment] 2019-06-21 09:59
Suggestion / request from MRDevDays @StephenHodgson , is to only import the Core, then pop up a prompt to let the user select any additional packages to import.

So update the default packages asset to only have Core + git.  Then once imported, popup the package window to import more.

**Comment by StephenHodgson** [comment] 2019-08-31 19:01
All the stuff to make this happen is there, we just need to have the window show itself using the `[InitializeOnLoad]` attribute to the inspector script.

**Closed** 2019-09-13 20:28 UTC
Labels: Bug
