### ISSUE TITLE
New scene setup broken with new platform system

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#493] opened 2020-04-03 16:50 UTC
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

If you start a new project and import the XRTK, when you try using "MixedRealityTooliit -> Configure", only the toolkit is added to the scene and the console is flooded with "Failed to start the X System!" errors

## To Reproduce

1. Create a new project
2. Add the 0.1.32 XRTK build
3. Create a new Scene
4. Use "Mixed Reality Toolkit -> Configure"
5. See error

## Expected behavior

Toolkit and Playspace rig should be added to the scene with no errors

## Actual behavior

![image](https://user-images.githubusercontent.com/1793042/78385234-733abd00-75d3-11ea-8e53-945580c951db.png)

## Your Setup (please complete the following information)

- Unity Version 2019.1.14
- XRTK Version 0.1.32

**Comment by StephenHodgson** [comment] 2020-04-03 17:01
Duplicate of #490

**Closed by StephenHodgson** 2020-04-03 17:01 UTC
Labels: Bug
