### ISSUE TITLE
Controller management required for situations where multiple data providers can exist on a single platform

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#247] opened 2019-07-17 22:48 UTC
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

With Windows Mixed Reality, OpenVR was for standalone and WMR was for UWP, there was a clear separation

Now with the addition of Oculus, we have situations where multiple data providers can compete for the controllers to manage, resulting in multiple data providers capturing and rendering the detected controllers.

Seems we need a higher level controller management framework to ensure that once a controller is activated and registered, it is ignored by any other provider.

## To Reproduce

1. Enable Joystick / OpenVR & Oculus on Windows Standalone (default behaviour)
2. Run the project with Oculus VR as the primary VR target
3. Observe that multiple controllers exist in the scene, some tracked and some not

## Expected behavior

Once a controller is active, it should be ignored by other data providers

## Actual behavior

Free for all, everyone registers and renders

## Your Setup (please complete the following information)

- Unity Version 2019.1.10
- XRTK Version 0.1.13

## Target Platform (please complete the following information)

- Windows Standalone

**Comment by SimonDarksideJ** [comment] 2019-07-18 07:09
Key Discussion point here, is what should be used as the central management point between all data providers? 

* Is it something new 
* or attached to the XRTK Entry point (Dictionary on the XRTK entry point for example)
* Or attached to the input system (A function call to validate if an input source exists for a given controller)

**Comment by StephenHodgson** [comment] 2019-09-15 14:05
Not really a bug. It's a matter of implementation details I suppose.

WMR and OpenVR seem to work just fine.

**Comment by StephenHodgson** [comment] 2019-09-24 22:29
Isn't this just a duplicate of #240?

**Closed** 2020-04-01 14:53 UTC
Labels: Bug
