### ISSUE TITLE
After Teleporting, pointer positions do not appear to update

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#775] opened 2021-01-28 14:10 UTC
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Hopefully, this is a simple knowledge issue, but I hit an issue regarding grabbing objects in a scene and placing it in the hand of the grabbed controller.

Whilst the user remains at 0 and walk around, there is no issue, grabbed objects are placed in the controller locations.

However, once a user has teleported, this ceases to work, even when parenting the grabbed object with the controller's parent.  The transforms for each object are identical but their positions are not.

## To Reproduce

1. Download sample project
[GrabbingAndTeleporting.zip](https://github.com/XRTK/XRTK-Core/files/5887798/GrabbingAndTeleporting.zip)

2. Check XR settings and run project
3. Grab each cube from current position - expected working ok
4. Teleport to a new position
5. Grab each cube again and notice they only move to the original, pre-teleport position.

## Expected behavior

It should be possible to use the Events position to position object relative to the controller that initiated the event

## Actual behavior

After teleporting, the new camera position is (under Playspace) is not taken into account, even if the object is parented to the playspace

## Screenshots

https://user-images.githubusercontent.com/1793042/106149738-832f1900-6172-11eb-9298-3bc16ff19875.mp4

## Additional Context

Here is the line where the grabbed object is parented to the controllers parent for reference:

```csharp
          transform.parent = eventData.InputSource.Pointers[0].Controller.Visualizer.GameObject.transform.parent;
```

Here is the full grab script that is used in the project for reference:

```csharp
using UnityEngine;
using XRTK.Definitions.InputSystem;
using XRTK.Definitions.Utilities;
using XRTK.EventDatum.Input;
using XRTK.Interfaces.InputSystem.Handlers;
using XRTK.SDK.Input.Handlers;
using XRTK.Services;

/// <summary>
/// A simple grabbable interaciton handler component. This component was just
/// created for demo purposes and is not part of the XRTK SDK. Feel free to use it as a starting
/// point for your own component until XRTK has a proper component for it.
/// </summary>
/// <remarks>This component is not optimized for production use.</remarks>
public class GrabParentUpdate : BaseInputHandler, IMixedRealityInputHandler, IMixedRealityInputHandler<MixedRealityPose>
{
    private bool isGripped;
    private float lerpTime;
    private Handedness gripHandedness;
    private bool lerpBackToStart;
    private Vector3 startPosition;
    private Quaternion startRotation;
    private Transform startParent;

    [SerializeField]
    private MixedRealityInputAction grabAction = MixedRealityInputAction.None;

    [SerializeField]
    private MixedRealityInputAction gripPoseAction = MixedRealityInputAction.None;

    [SerializeField]
    [Tooltip("If the distance to the grabbed object is above the threshold it will lerp towards the grab pose.")]
    private float lerpDistanceThreshold = .05f;

    [SerializeField]
    [Tooltip("Grab pose lerp duration.")]
    private float lerpDuration = 1f;

    [SerializeField]
    [Tooltip("Grip pose offset for the object.")]
    private Vector3 gripPositionOffset = Vector3.zero;

    private void Awake()
    {
        startPosition = transform.position;
        startRotation = transform.rotation;
        startParent = transform.parent;
    }

    private void Update()
    {
        if (lerpBackToStart)
        {
            var fraction = lerpTime / lerpDuration;
            transform.position = Vector3.Slerp(transform.position, startPosition, fraction);
            transform.rotation = Quaternion.Slerp(transform.rotation, startRotation, fraction);
            lerpBackToStart = fraction < 1f;
            lerpTime += Time.deltaTime;
        }
    }

    public void OnInputChanged(InputEventData<MixedRealityPose> eventData)
    {
        if (eventData.used)
        {
            return;
        }

        if (eventData.Handedness == gripHandedness && eventData.MixedRealityInputAction == gripPoseAction && isGripped)
        {
            if (Vector3.Distance(transform.position, eventData.InputData.Position) <= lerpDistanceThreshold)
            {
                transform.position = eventData.InputData.Position + eventData.InputData.Rotation * gripPositionOffset;
                transform.rotation = eventData.InputData.Rotation;
            }
            else
            {
                var fraction = lerpTime / lerpDuration;
                transform.position = Vector3.Slerp(transform.position, eventData.InputData.Position + eventData.InputData.Rotation * gripPositionOffset, fraction);
                transform.rotation = Quaternion.Slerp(transform.rotation, eventData.InputData.Rotation, fraction);
                lerpTime += Time.deltaTime;
            }
        }
    }

    public void OnInputDown(InputEventData eventData)
    {
        if (eventData.used)
        {
            return;
        }

        if (!isGripped && eventData.MixedRealityInputAction == grabAction)
        {
            isGripped = true;
            gripHandedness = eventData.Handedness;
            transform.parent = eventData.InputSource.Pointers[0].Controller.Visualizer.GameObject.transform.parent;

            if (MixedRealityToolkit.IsInitialized &&
            MixedRealityToolkit.InputSystem != null)
            {
                MixedRealityToolkit.InputSystem.Register(gameObject);
            }

            lerpTime = 0f;
            eventData.Use();
        }
    }

    public void OnInputUp(InputEventData eventData)
    {
        if (eventData.used || eventData.Handedness != gripHandedness)
        {
            return;
        }

        if (eventData.MixedRealityInputAction == grabAction)
        {
            isGripped = false;
            MixedRealityToolkit.InputSystem?.Unregister(gameObject);
            eventData.Use();

            lerpTime = 0f;
            lerpBackToStart = true;
            transform.parent = startParent;
        }
    }
}
```

**Comment by FejZa** [comment] 2021-01-28 17:23
Thanks for the detailed report.

**Comment by StephenHodgson** [comment] 2021-04-20 03:28
@SimonDarksideJ this is the intended behavior.
The visualizers parent is the users local play space frame of reference.

I suggest not even re-parenting the object, but instead using a solver or constraint to perform the desired action.
Could you better describe exactly what you're trying to accomplish here when you grab the cubes?

If you're just trying to synchronize the cube with your controller just use the `eventData.InputSource.Pointers[0].Controller.Visualizer.GameObject.transform.position` (although you should really be using the `IMixedRealityPointerHandler` if you're going to do anything with pointers).

If you're trying to synchronize the cube object with your local frame of reference you could set the position of the cube to the controller's transform position, then update the parent to the user's body `Scene/MixedRealityPlayspace/PlayerBody`

**Comment by SimonDarksideJ** [comment] 2021-04-20 10:49
I think you missed the point @StephenHodgson 

A simple fact is that the EVENTS the pointers emit expose the incorrect position after teleporting.
It works fine before teleporting but after teleporting the positions are wrong

**Comment by StephenHodgson** [comment] 2021-04-20 14:31
@SimonDarksideJ specifically which property of the pointer is incorrect here?

**Comment by SimonDarksideJ** [comment] 2021-04-20 14:50
> Pointers don't emit any events afaik.

They don't emit events correct, but the pointer data and its state is shared within an event.

**Comment by StephenHodgson** [comment] 2021-04-20 14:51
You're not even using the pointer event data bc you haven't implemented the pointer handler in this class

**Comment by SimonDarksideJ** [comment] 2021-04-20 17:04
The issue isn't the script, the script is just their to demonstrate the issue with the pointer event data location.

**Comment by StephenHodgson** [comment] 2021-04-20 17:08
I see issues with the script. You're not even getting the pointer event data through the pointer handler.

**Comment by SimonDarksideJ** [comment] 2021-04-20 17:34
Let me get back to you on that one :D

**Comment by StephenHodgson** [comment] 2021-05-16 19:53
Going to close this. Reopen when you're ready to update the information @SimonDarksideJ

**Closed by StephenHodgson** 2021-05-16 19:53 UTC
Labels: By design
